name: comment
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.6.0
  firebase_database: ^7.2.1
  get: ^4.1.4
  get_storage: ^2.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/